(()=>{
 const cfg=window.APP_CONFIG,$=s=>document.querySelector(s);let auth,db,users=[],view=[],payments=[],presence={},currentAdmin=null;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const mask=c=>{c=String(c||'').replace(/\D/g,'');return c.length===11?`***.***.${c.slice(6,9)}-${c.slice(9)}`:'—'};
 const date=v=>v?new Date(v).toLocaleString('pt-BR'):'—', inputDate=v=>v?new Date(v).toISOString().slice(0,10):'';
 const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const expired=u=>u.status==='ativo'&&u.expiresAt&&new Date(u.expiresAt)<new Date();
 const isOnline=u=>presence[u.uid]?.online===true;
 const presenceText=u=>isOnline(u)?'Online agora':(presence[u.uid]?.lastSeen?'Offline • '+date(presence[u.uid].lastSeen):'Nunca entrou');
 function stats(){const a=users;const online=a.filter(isOnline);$('#sOnline').textContent=online.length;$('#sOnlineDetail').textContent=online.length===1?'1 pessoa no e-book':online.length+' pessoas no e-book';$('#sUsers').textContent=a.length;$('#sActive').textContent=a.filter(u=>u.status==='ativo'&&!expired(u)).length;$('#sPending').textContent=a.filter(u=>u.status==='pendente').length;$('#sBlocked').textContent=a.filter(u=>u.status==='bloqueado').length;$('#sExpired').textContent=a.filter(expired).length;const approved=payments.filter(p=>p.status==='approved');$('#sRevenue').textContent=money(approved.reduce((n,p)=>n+Number(p.amount||0),0));$('#sPaid').textContent=approved.length;$('#sPayPending').textContent=payments.filter(p=>p.status==='pending').length}
 function draw(a){view=a;stats();$('#body').innerHTML=a.map(u=>`<tr><td><b>${esc(u.name)}</b><small>${esc(u.email)}</small><small>UID: ${esc((u.uid||'').slice(0,10))}…</small></td><td>${esc(u.phone||'—')}</td><td>${mask(u.cpf)}</td><td>${esc(cfg.plans?.[u.plan]?.name||u.plan||'Sem plano')}</td><td><span class="pill ${expired(u)?'bloqueado':esc(u.status||'pendente')}">${expired(u)?'vencido':esc(u.status||'pendente')}</span></td><td>${date(u.expiresAt)}</td><td><span class="presence ${isOnline(u)?'online':'offline'}"><i></i>${presenceText(u)}</span></td><td>${date(u.lastAccess)}</td><td><div class="row-actions"><button data-edit="${u.uid}">Editar</button><button data-add="30" data-id="${u.uid}">+30d</button><button data-add="90" data-id="${u.uid}">+90d</button><button data-block="${u.uid}">Bloquear</button><button data-copy="${u.uid}">UID</button></div></td></tr>`).join('')||'<tr><td colspan="9">Nenhum usuário cadastrado.</td></tr>';bindRows()}
 function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openUser(b.dataset.edit));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>extend(b.dataset.id,+b.dataset.add));document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>persist(b.dataset.block,{status:'bloqueado',updatedAt:firebase.database.ServerValue.TIMESTAMP}));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);alert('UID copiado.')})}
 function filter(){const q=$('#search').value.toLowerCase(),s=$('#status').value;draw(users.filter(u=>{const statusOk=!s||(s==='vencido'?expired(u):s==='online'?isOnline(u):s==='offline'?!isOnline(u):u.status===s);return statusOk&&JSON.stringify(u).toLowerCase().includes(q)}))}
 function openUser(id){const u=users.find(x=>x.uid===id);if(!u)return;const f=$('#userForm');Object.entries(u).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=k==='expiresAt'?inputDate(v):(v??'')});f.elements.id.value=id;$('#modalTitle').textContent='Editar usuário';$('#deleteUser').style.display='inline-block';$('#modal').classList.add('open')}
 async function persist(id,data){await db.ref('users/'+id).update(data)}
 async function extend(id,days){const u=users.find(x=>x.uid===id);let base=new Date();if(u?.expiresAt&&new Date(u.expiresAt)>base)base=new Date(u.expiresAt);base.setDate(base.getDate()+days);await persist(id,{status:'ativo',expiresAt:base.toISOString(),updatedAt:firebase.database.ServerValue.TIMESTAMP})}
 async function submit(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),id=d.id;delete d.id;d.cpf=String(d.cpf||'').replace(/\D/g,'');d.expiresAt=d.expiresAt?new Date(d.expiresAt+'T23:59:59').toISOString():'';d.updatedAt=firebase.database.ServerValue.TIMESTAMP;try{await persist(id,d);$('#modal').classList.remove('open')}catch(err){alert(err.message)}}
 async function remove(){const id=$('#userForm').elements.id.value;if(!id||!confirm('Excluir este cadastro do Realtime Database? A conta no Authentication não será apagada.'))return;await db.ref('users/'+id).remove();$('#modal').classList.remove('open')}
 function exportCsv(rows,name){const blob=new Blob(['\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(';')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
 function usersCsv(){exportCsv([['UID','Nome','Email','Telefone','CPF mascarado','Plano','Status','Vencimento','Função'],...view.map(u=>[u.uid,u.name,u.email,u.phone,mask(u.cpf),u.plan,u.status,u.expiresAt,u.role])],'usuarios-personal-trainer.csv')}
 function paymentsCsv(){exportCsv([['ID','Cliente','Email','Plano','Forma','Parcelas','Valor','Status','Criado','Aprovado'],...payments.map(p=>[p.id,p.userName,p.userEmail,p.planName||p.planId,p.paymentMethod||'pix',p.installments||1,p.amount,p.status,p.createdAt,p.approvedAt])],'pagamentos-personal-trainer.csv')}
 function drawPayments(){const f=$('#paymentStatus')?.value||'',m=$('#paymentMethod')?.value||'',a=payments.filter(p=>(!f||p.status===f)&&(!m||(p.paymentMethod||'pix')===m));$('#paymentsBody').innerHTML=a.map(p=>{const reversible=['approved','pending','in_process','authorized'].includes(p.status);const label=p.status==='approved'?'Reembolsar':'Cancelar';const method=(p.paymentMethod||'pix')==='card'?'Cartão':'Pix';return `<tr><td><b>${esc(p.userName||'—')}</b><small>${esc(p.userEmail||'')}</small></td><td>${esc(p.planName||p.planId||'—')}</td><td>${method}</td><td>${method==='Cartão'?(p.installments||1)+'x':'—'}</td><td>${money(p.amount)}</td><td><span class="pill ${p.status==='approved'?'ativo':p.status==='pending'?'pendente':'bloqueado'}">${esc(p.status||'—')}</span></td><td>${date(p.createdAt)}</td><td>${date(p.approvedAt)}</td><td><small>${esc(p.mercadoPagoId||p.id||'—')}</small></td><td>${reversible?`<button class="payment-cancel" data-payment-cancel="${esc(p.id)}" data-payment-status="${esc(p.status)}">${label}</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="10">Nenhum pagamento encontrado.</td></tr>';document.querySelectorAll('[data-payment-cancel]').forEach(b=>b.onclick=()=>cancelPayment(b));stats()}
 async function adminApi(path,opts={}){if(!currentAdmin)throw new Error('Faça login novamente.');const token=await currentAdmin.getIdToken();const base=String(cfg.functionsBaseUrl||'').replace(/\/$/,'');if(!base)throw new Error('URL do backend não configurada no painel.');const r=await fetch(base+path,{...opts,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,...(opts.headers||{})}});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'Operação não concluída.');return out}
 async function cancelPayment(button){const id=button.dataset.paymentCancel,status=button.dataset.paymentStatus;const refund=status==='approved';const text=refund?'Este pagamento já foi aprovado. O valor será reembolsado ao cliente e o acesso vinculado será bloqueado. Continuar?':'Cancelar esta cobrança pendente?';if(!confirm(text))return;const original=button.textContent;button.disabled=true;button.textContent=refund?'Reembolsando…':'Cancelando…';try{const out=await adminApi('/admin/cancelPayment',{method:'POST',body:JSON.stringify({paymentId:id})});alert(out.action==='refund'?'Reembolso solicitado com sucesso.':'Pagamento cancelado com sucesso.')}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent=original}}
 function openAdminMenu(){$('#adminMenu').classList.add('open');$('#adminMenuShade').classList.add('open');$('#adminMenu').setAttribute('aria-hidden','false');$('#adminMenuToggle').setAttribute('aria-expanded','true')}
 function closeAdminMenu(){$('#adminMenu').classList.remove('open');$('#adminMenuShade').classList.remove('open');$('#adminMenu').setAttribute('aria-hidden','true');$('#adminMenuToggle').setAttribute('aria-expanded','false')}
 function init(){firebase.initializeApp(cfg.firebase);auth=firebase.auth();db=firebase.database();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});auth.onAuthStateChanged(async u=>{currentAdmin=u;if(!u){$('#loginGate').classList.remove('hidden');closeAdminMenu();return}const me=(await db.ref('users/'+u.uid).once('value')).val();if(me?.role!=='admin'){alert('Conta sem permissão de administrador. Defina role como admin no Firebase.');await auth.signOut();return}$('#loginGate').classList.add('hidden');$('#adminName').textContent=me.name||'Administrador';$('#adminEmail').textContent=me.email||u.email||'';db.ref('users').on('value',s=>{users=Object.entries(s.val()||{}).map(([uid,v])=>({uid,...v})).sort((a,b)=>String(a.name).localeCompare(String(b.name)));filter()});db.ref('presence').on('value',s=>{presence=s.val()||{};filter()});db.ref('payments').on('value',s=>{payments=Object.entries(s.val()||{}).map(([id,v])=>({id,...v})).sort((x,y)=>new Date(y.createdAt||0)-new Date(x.createdAt||0));drawPayments()})})}
 document.addEventListener('DOMContentLoaded',()=>{$('#search').oninput=filter;$('#status').onchange=filter;$('#paymentStatus').onchange=drawPayments;$('#paymentMethod').onchange=drawPayments;$('#newUser').style.display='none';$('#close').onclick=()=>$('#modal').classList.remove('open');$('#userForm').onsubmit=submit;$('#deleteUser').onclick=remove;$('#exportCsv').onclick=usersCsv;$('#exportPayments').onclick=paymentsCsv;$('#refresh').onclick=()=>location.reload();$('#logout').onclick=()=>auth.signOut();$('#adminMenuToggle').onclick=openAdminMenu;$('#adminMenuClose').onclick=closeAdminMenu;$('#adminMenuShade').onclick=closeAdminMenu;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAdminMenu()});$('#loginForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await auth.signInWithEmailAndPassword(d.email,d.password)}catch{alert('E-mail ou senha inválidos.')}};init()})
})();

;(()=>{let deferredPrompt=null;const box=()=>document.getElementById('installApp');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;box()?.classList.remove('hidden')});window.addEventListener('appinstalled',()=>{deferredPrompt=null;box()?.classList.add('hidden')});document.addEventListener('DOMContentLoaded',()=>{document.getElementById('installNow')?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;box()?.classList.add('hidden')});document.getElementById('installDismiss')?.addEventListener('click',()=>box()?.classList.add('hidden'));if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(console.error))})})();
