(()=>{
 const cfg=window.APP_CONFIG,$=s=>document.querySelector(s);let auth,db,users=[],view=[],payments=[],presence={},currentAdmin=null;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const mask=c=>{c=String(c||'').replace(/\D/g,'');return c.length===11?`***.***.${c.slice(6,9)}-${c.slice(9)}`:'—'};
 const date=v=>v?new Date(v).toLocaleString('pt-BR'):'—', inputDate=v=>v?new Date(v).toISOString().slice(0,10):'';
 const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const expired=u=>u.status==='ativo'&&u.expiresAt&&new Date(u.expiresAt)<new Date();
 const isOnline=u=>presence[u.uid]?.online===true;
 const presenceText=u=>isOnline(u)?'Online agora':(presence[u.uid]?.lastSeen?'Offline • '+date(presence[u.uid].lastSeen):'Nunca entrou');
 function stats(){const a=users;const online=a.filter(isOnline);$('#sOnline').textContent=online.length;$('#sOnlineDetail').textContent=online.length===1?'1 pessoa no e-book':online.length+' pessoas no e-book';$('#sUsers').textContent=a.length;$('#sActive').textContent=a.filter(u=>u.status==='ativo'&&!expired(u)).length;$('#sPending').textContent=a.filter(u=>u.status==='pendente').length;$('#sBlocked').textContent=a.filter(u=>u.status==='bloqueado').length;$('#sExpired').textContent=a.filter(expired).length;const approved=payments.filter(p=>p.status==='approved');$('#sRevenue').textContent=money(approved.reduce((n,p)=>n+Number(p.amount||0),0));$('#sPaid').textContent=approved.length;$('#sPayPending').textContent=payments.filter(p=>p.status==='pending').length}
 function draw(a){view=a;stats();$('#body').innerHTML=a.map(u=>`<tr><td><b>${esc(u.name)}</b><small>${esc(u.email)}</small><small>UID: ${esc((u.uid||'').slice(0,10))}…</small></td><td>${esc(u.phone||'—')}</td><td>${mask(u.cpf)}</td><td>${esc(cfg.plans?.[u.plan]?.name||u.plan||'Sem plano')}</td><td><span class="pill ${expired(u)?'bloqueado':esc(u.status||'pendente')}">${expired(u)?'vencido':esc(u.status||'pendente')}</span></td><td>${date(u.expiresAt)}</td><td><span class="presence ${isOnline(u)?'online':'offline'}"><i></i>${presenceText(u)}</span></td><td>${date(u.lastAccess)}</td><td><button class="user-gear" data-user-actions="${u.uid}" aria-label="Abrir configurações de ${esc(u.name)}" title="Configurações">⚙️</button></td></tr>`).join('')||'<tr><td colspan="9">Nenhum usuário cadastrado.</td></tr>';bindRows()}
 function bindRows(){document.querySelectorAll('[data-user-actions]').forEach(b=>b.onclick=()=>openUserActions(b.dataset.userActions))}
 function openUserActions(id){const u=users.find(x=>x.uid===id);if(!u)return;$('#actionsUserName').textContent=u.name||'Usuário';$('#actionsUserEmail').textContent=u.email||'';const box=$('#userActions');box.dataset.uid=id;$('#actionBlock').textContent=u.status==='bloqueado'?'Desbloquear acesso':'Bloquear acesso';$('#actionBlock').classList.toggle('danger',u.status!=='bloqueado');$('#actionsModal').classList.add('open')}
 function closeUserActions(){$('#actionsModal').classList.remove('open')}
 async function runUserAction(action){const id=$('#userActions').dataset.uid;if(!id)return;try{if(action==='edit'){closeUserActions();openUser(id);return}if(action==='copy'){await navigator.clipboard.writeText(id);alert('UID copiado.');return}if(action==='block'){const u=users.find(x=>x.uid===id);await persist(id,{status:u?.status==='bloqueado'?'ativo':'bloqueado',updatedAt:firebase.database.ServerValue.TIMESTAMP});closeUserActions();return}const days=Number(action);if([30,90,365].includes(days)){await extend(id,days);closeUserActions()}}catch(e){alert(e.message||'Não foi possível concluir a ação.')}}
 function filter(){const q=$('#search').value.toLowerCase(),s=$('#status').value;draw(users.filter(u=>{const statusOk=!s||(s==='vencido'?expired(u):s==='online'?isOnline(u):s==='offline'?!isOnline(u):u.status===s);return statusOk&&JSON.stringify(u).toLowerCase().includes(q)}))}
 function openUser(id){const u=users.find(x=>x.uid===id);if(!u)return;const f=$('#userForm');Object.entries(u).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=k==='expiresAt'?inputDate(v):(v??'')});f.elements.id.value=id;$('#modalTitle').textContent='Editar usuário';$('#deleteUser').style.display='inline-block';$('#modal').classList.add('open')}
 async function persist(id,data){await db.ref('users/'+id).update(data)}
 async function extend(id,days){const u=users.find(x=>x.uid===id);let base=new Date();if(u?.expiresAt&&new Date(u.expiresAt)>base)base=new Date(u.expiresAt);base.setDate(base.getDate()+days);await persist(id,{status:'ativo',expiresAt:base.toISOString(),updatedAt:firebase.database.ServerValue.TIMESTAMP})}
 async function submit(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),id=d.id;delete d.id;d.cpf=String(d.cpf||'').replace(/\D/g,'');d.expiresAt=d.expiresAt?new Date(d.expiresAt+'T23:59:59').toISOString():'';d.updatedAt=firebase.database.ServerValue.TIMESTAMP;try{await persist(id,d);$('#modal').classList.remove('open')}catch(err){alert(err.message)}}
 async function remove(){const id=$('#userForm').elements.id.value;if(!id||!confirm('Excluir este cadastro do Realtime Database? A conta no Authentication não será apagada.'))return;await db.ref('users/'+id).remove();$('#modal').classList.remove('open')}
 function exportCsv(rows,name){const blob=new Blob(['\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(';')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
 function usersCsv(){exportCsv([['UID','Nome','Email','Telefone','CPF mascarado','Plano','Status','Vencimento','Função'],...view.map(u=>[u.uid,u.name,u.email,u.phone,mask(u.cpf),u.plan,u.status,u.expiresAt,u.role])],'usuarios-personal-trainer.csv')}
 function paymentsCsv(){exportCsv([['ID','Cliente','Email','Plano','Forma','Parcelas','Valor','Status','Criado','Aprovado'],...payments.map(p=>[p.id,p.userName,p.userEmail,p.planName||p.planId,p.paymentMethod||p.paymentTypeId||'pix',p.installments||1,p.amount,p.status,p.createdAt,p.approvedAt])],'pagamentos-personal-trainer.csv')}
 function paymentMethodLabel(p){const m=p.paymentMethod||p.paymentTypeId||'pix';if(m==='debit_card')return 'Débito';if(m==='credit_card'||m==='card')return 'Crédito';return 'Pix'}
 function drawPayments(){const f=$('#paymentStatus')?.value||'',m=$('#paymentMethod')?.value||'',a=payments.filter(p=>{const pm=p.paymentMethod==='card'?'credit_card':(p.paymentMethod||'pix');return(!f||p.status===f)&&(!m||pm===m)});$('#paymentsBody').innerHTML=a.map(p=>{const reversible=['approved','pending','in_process','authorized'].includes(p.status);const label=p.status==='approved'?'Reembolsar':'Cancelar';const method=paymentMethodLabel(p);return `<tr><td><b>${esc(p.userName||'—')}</b><small>${esc(p.userEmail||'')}</small></td><td>${esc(p.planName||p.planId||'—')}</td><td>${method}</td><td>${method==='Crédito'?(p.installments||1)+'x':'—'}</td><td>${money(p.amount)}</td><td><span class="pill ${p.status==='approved'?'ativo':p.status==='pending'?'pendente':'bloqueado'}">${esc(p.status||'—')}</span></td><td>${date(p.createdAt)}</td><td>${date(p.approvedAt)}</td><td><small>${esc(p.mercadoPagoId||p.id||'—')}</small></td><td>${reversible?`<button class="payment-cancel" data-payment-cancel="${esc(p.id)}" data-payment-status="${esc(p.status)}">${label}</button>`:(p.status==='refunded'?'<span class="pill ativo">Reembolsado</span>':'—')}</td></tr>`}).join('')||'<tr><td colspan="10">Nenhum pagamento encontrado.</td></tr>';document.querySelectorAll('[data-payment-cancel]').forEach(b=>b.onclick=()=>cancelPayment(b));stats()}
 async function adminApi(path,opts={}){if(!currentAdmin)throw new Error('Faça login novamente.');const token=await currentAdmin.getIdToken();const base=String(cfg.functionsBaseUrl||'').replace(/\/$/,'');if(!base)throw new Error('URL do backend não configurada no painel.');const r=await fetch(base+path,{...opts,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,...(opts.headers||{})}});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'Operação não concluída.');return out}
 async function cancelPayment(button){const id=button.dataset.paymentCancel,status=button.dataset.paymentStatus;const refund=status==='approved';const text=refund?'Este pagamento já foi aprovado. O valor será reembolsado ao cliente e o acesso vinculado será bloqueado. Continuar?':'Cancelar esta cobrança pendente?';if(!confirm(text))return;const original=button.textContent;button.disabled=true;button.textContent=refund?'Reembolsando…':'Cancelando…';try{const out=await adminApi('/admin/cancelPayment',{method:'POST',body:JSON.stringify({paymentId:id})});alert(out.message||(out.action==='refund'?'Reembolso realizado com sucesso.':'Pagamento cancelado com sucesso.'));const item=payments.find(p=>p.id===id);if(item)item.status=out.status;drawPayments()}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent=original}}
 function openAdminMenu(){$('#adminMenu').classList.add('open');$('#adminMenuShade').classList.add('open');$('#adminMenu').setAttribute('aria-hidden','false');$('#adminMenuToggle').setAttribute('aria-expanded','true')}
 function closeAdminMenu(){$('#adminMenu').classList.remove('open');$('#adminMenuShade').classList.remove('open');$('#adminMenu').setAttribute('aria-hidden','true');$('#adminMenuToggle').setAttribute('aria-expanded','false')}
 const GUIDE_STEPS=[
  ['primeiros_passos','Passo 1 — Primeiros passos'],['aquecimento','Passo 2 — Aquecimento'],['agachamento','Passo 3 — Agachamento básico'],['flexao','Passo 4 — Flexão adaptada'],['prancha','Passo 5 — Prancha abdominal'],['recuperacao','Passo 6 — Recuperação']
 ];
 function drawAppUpdate(values={}){
  $('#latestVersion').value=values.latestVersion||'';$('#minimumVersion').value=values.minimumVersion||'';$('#apkUrl').value=values.apkUrl||'';$('#updateMessage').value=values.message||'';$('#forceUpdate').checked=values.forceUpdate===true;
 }
 async function saveAppUpdate(){
  const btn=$('#saveAppUpdate'),status=$('#updateSaveStatus');const latest=$('#latestVersion').value.trim(),minimum=$('#minimumVersion').value.trim(),apkUrl=$('#apkUrl').value.trim();
  if(!latest||!minimum)return alert('Informe a última versão e a versão mínima.');if($('#forceUpdate').checked&&!apkUrl)return alert('Informe o link direto do APK antes de forçar a atualização.');
  btn.disabled=true;btn.textContent='Salvando…';status.textContent='';try{await db.ref('appUpdate').set({latestVersion:latest,minimumVersion:minimum,apkUrl,message:$('#updateMessage').value.trim(),forceUpdate:$('#forceUpdate').checked,updatedAt:firebase.database.ServerValue.TIMESTAMP,updatedBy:currentAdmin.uid});status.textContent='✓ Configuração salva. Aplicativos antigos receberão o aviso automaticamente.';status.className='guide-save-status ok'}catch(e){status.textContent=e.message||'Não foi possível salvar.';status.className='guide-save-status bad'}finally{btn.disabled=false;btn.textContent='Salvar atualização'}
 }
 function drawGuideVideoFields(values={}){
  const box=$('#guideVideoFields');if(!box)return;
  box.innerHTML=GUIDE_STEPS.map(([id,title])=>`<label class="guide-link-field"><span>${title}</span><input type="url" inputmode="url" data-guide-id="${id}" value="${esc(values[id]?.url||'')}" placeholder="https://www.youtube.com/watch?v=..."><small>${values[id]?.updatedAt?'Atualizado em '+date(values[id].updatedAt):'Cole o link completo do YouTube'}</small></label>`).join('');
 }
 async function saveGuideVideos(){
  const btn=$('#saveGuideVideos'),status=$('#guideSaveStatus');btn.disabled=true;btn.textContent='Salvando…';status.textContent='';
  try{
   const updates={};document.querySelectorAll('[data-guide-id]').forEach(input=>{const id=input.dataset.guideId,url=String(input.value||'').trim();updates[id]={url,title:GUIDE_STEPS.find(x=>x[0]===id)?.[1]||id,updatedAt:firebase.database.ServerValue.TIMESTAMP}});
   await db.ref('guideVideos').set(updates);status.textContent='✓ Links salvos. O aplicativo do cliente atualizará automaticamente.';status.className='guide-save-status ok';
  }catch(e){status.textContent=e.message||'Não foi possível salvar os links.';status.className='guide-save-status bad'}finally{btn.disabled=false;btn.textContent='Salvar todos os vídeos'}
 }
 function init(){firebase.initializeApp(cfg.firebase);auth=firebase.auth();db=firebase.database();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});auth.onAuthStateChanged(async u=>{currentAdmin=u;if(!u){$('#loginGate').classList.remove('hidden');closeAdminMenu();return}const me=(await db.ref('users/'+u.uid).once('value')).val();if(me?.role!=='admin'){alert('Conta sem permissão de administrador. Defina role como admin no Firebase.');await auth.signOut();return}$('#loginGate').classList.add('hidden');$('#adminName').textContent=me.name||'Administrador';$('#adminEmail').textContent=me.email||u.email||'';db.ref('users').on('value',s=>{users=Object.entries(s.val()||{}).map(([uid,v])=>({uid,...v})).sort((a,b)=>String(a.name).localeCompare(String(b.name)));filter()});db.ref('presence').on('value',s=>{presence=s.val()||{};filter()});db.ref('payments').on('value',s=>{payments=Object.entries(s.val()||{}).map(([id,v])=>({id,...v})).sort((x,y)=>new Date(y.createdAt||0)-new Date(x.createdAt||0));drawPayments()});db.ref('guideVideos').on('value',s=>drawGuideVideoFields(s.val()||{}));db.ref('appUpdate').on('value',s=>drawAppUpdate(s.val()||{}))})}
 document.addEventListener('DOMContentLoaded',()=>{$('#search').oninput=filter;$('#status').onchange=filter;$('#paymentStatus').onchange=drawPayments;$('#paymentMethod').onchange=drawPayments;$('#newUser').style.display='none';$('#close').onclick=()=>$('#modal').classList.remove('open');$('#actionsClose').onclick=closeUserActions;$('#actionsModal').onclick=e=>{if(e.target.id==='actionsModal')closeUserActions()};document.querySelectorAll('[data-user-action]').forEach(b=>b.onclick=()=>runUserAction(b.dataset.userAction));$('#userForm').onsubmit=submit;$('#deleteUser').onclick=remove;$('#exportCsv').onclick=usersCsv;$('#exportPayments').onclick=paymentsCsv;$('#saveGuideVideos').onclick=saveGuideVideos;$('#saveAppUpdate').onclick=saveAppUpdate;$('#refresh').onclick=()=>location.reload();$('#logout').onclick=()=>auth.signOut();$('#adminMenuToggle').onclick=openAdminMenu;$('#adminMenuClose').onclick=closeAdminMenu;$('#adminMenuShade').onclick=closeAdminMenu;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAdminMenu()});$('#loginForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await auth.signInWithEmailAndPassword(d.email,d.password)}catch{alert('E-mail ou senha inválidos.')}};init()})
})();

;(()=>{let deferredPrompt=null;const box=()=>document.getElementById('installApp');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;box()?.classList.remove('hidden')});window.addEventListener('appinstalled',()=>{deferredPrompt=null;box()?.classList.add('hidden')});document.addEventListener('DOMContentLoaded',()=>{document.getElementById('installNow')?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;box()?.classList.add('hidden')});document.getElementById('installDismiss')?.addEventListener('click',()=>box()?.classList.add('hidden'));if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(console.error))})})();
